samples: "resources/samples/sample.tsv"

trimmomatic:
  adapters: "resources/Trimmomatic-0-2.39/adapters/NexteraPE-PE.fa"
  illuminaclip: "2:30:10:2:True"
  leading: 3
  trailing: 3
  slidingwindow: "4:20"  # Gleitendes Fenster von 4 bp, Mindestqualität 20
  minlen: 36

kraken-db: /buffer/ag_bsc/pmsb_workflows_2025/team4_ensemble_assembly/kraken-db2

# --- Paths to external reference data ---
contamination: "/buffer/ag_bsc/pmsb_workflows_2025/team4_ensemble_assembly/ensembleassembly/resources/genomes/GCF_009914755.1_T2T-CHM13v2.0_genomic.fna"

busco_lineage: "enterobacterales_odb10"

spades:
  options: 


stages:
  - denovo
  - final

normalize_reads:
  target_depth: 50
  min_depth: 5